name: job-server
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/job-server
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - job-server
      - setup-job-server
