name: setup-mpc-alerts
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-alerts
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-common
commands:
  deploy-public:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-alerts
dependencies:
  - setup-mpc-common
