name: setup-mpc-server
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-server
      - '278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-common:latest 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-tools:latest'
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-server
dependencies:
  - setup-mpc-common
  - setup-tools
