name: setup-mpc-server
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - setup-mpc-server
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-server
dependencies:
  - setup-mpc-common
  - setup-tools