version: '3'
services:
  setup-mpc-server:
    build:
      context: ..
      dockerfile: setup-mpc-server/Dockerfile
    image: aztec/setup-mpc-server
    ports:
      - "8080:80"
    volumes:
      - .:/usr/src/app