version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
  aws-cli: circleci/aws-cli@0.1.1
jobs:
  build_and_push_setup_tools:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule init && git submodule update
      - setup_remote_docker
      - aws-ecr/build-image:
          dockerfile: ./setup-tools/Dockerfile
          repo: setup-tools
          path: setup-tools
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: setup-tools

workflows:
  build_and_push_image:
    jobs:
      - build_and_push_setup_tools:
          context: global