version: 2.1
jobs:
  build_build_image:
    docker:
      - image: circleci/python:3.6.7-jessie
    steps:
      - checkout
      - run:
          name: 'Check if build image needs rebuilding'
          command: |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            echo "Last successful commit: ${LAST_SUCCESSFUL_COMMIT}"
            if ! git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q ^build-image/.*; then circleci step halt; fi
      - setup_remote_docker
      - run:
          name: 'Login to dockerhub'
          command: docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"
      - run:
          name: 'Build and push build image'
          command: |
            cd build-image
            docker build -t aztecprotocol/build-image .
            docker push aztecprotocol/build-image:latest

  build_and_test:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - run:
          name: 'Setup environment variables'
          command: |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=1"
            echo export LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'` >> $BASH_ENV
            cat $BASH_ENV
      - checkout
      - run:
          name: 'Pull submodules'
          command: git submodule init && git submodule update
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: 'ECR login'
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: 'Build'
          command: |
            mbt build diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1}
      - run:
          name: 'Deploy if master'
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then exit 0; fi
            mbt run-in diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1} -m deploy --fail-fast
            docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"
            mbt run-in diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1} -m deploy-public --fail-fast

workflows:
  build_and_push_images:
    jobs:
      - build_build_image
      - build_and_test:
          requires:
            - build_build_image
