version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.7-jessie
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule init && git submodule update
      - setup_remote_docker
      - run:
          name: "Install aws cli"
          command: sudo pip install awscli --upgrade -q
      - run:
          name: "Install mbt"
          command : |
            sudo curl -L -o /usr/local/bin/mbt https://bintray.com/buddyspike/bin/download_file?file_path=mbt_linux_x86_64/0.22.0/0.22.0/mbt_linux_x86_64
            sudo chmod +x /usr/local/bin/mbt
      - run:
          name: "ECR login"
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: "Build"
          command : |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=completed&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
              # First commit in a branch
              mbt build branch $CIRCLE_BRANCH
            else
              mbt build diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1}
            fi

workflows:
  build_and_push_images:
    jobs:
      - build-and-test:
          context: global
      # - build_and_push_images:
      #     context: global
      #     filters:
      #       branches:
      #         only: master