version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          context: global
          create-repo: true
          path: setup-tools
          repo: setup-tools