version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule init && git submodule update
      - setup_remote_docker
      - run:
          name: "Install aws cli"
          command: sudo pip install awscli --upgrade
      - run:
          name: "Install mbt"
          command : |
            curl -L -o /usr/local/bin/mbt https://bintray.com/buddyspike/bin/download_file?file_path=mbt_linux_x86_64/0.22.0/0.22.0/mbt_linux_x86_64
            chmod +x /usr/local/bin/mbt
      - run:
          name: "ECR login"
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: "Build"
          command : |
            mbt build commit ${CIRCLE_SHA1} --content

workflows:
  build_and_push_images:
    jobs:
      - build-and-test:
          context: global
      # - build_and_push_images:
      #     context: global
      #     filters:
      #       branches:
      #         only: master