version: 2.1
jobs:
  build_and_test:
    docker:
      - image: aztecprotocol/build-image
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule init && git submodule update
      - setup_remote_docker
      - run:
          name: "ECR login"
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: "Build"
          command : |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            mbt build diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1} --fail-fast
      - run:
          name: "Deploy if master"
          command : |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then exit 0; fi
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            mbt run-in diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1} -m deploy --fail-fast
            docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"
            mbt run-in diff --from ${LAST_SUCCESSFUL_COMMIT} --to ${CIRCLE_SHA1} -m deploy-public --fail-fast

workflows:
  build_and_push_images:
    jobs:
      - build_and_test:
          context: global