name: setup-mpc-client
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - setup-mpc-client
      - aztecprotocol
commands:
  deploy-public:
    cmd: ../ci-scripts/deploy-public.sh
    args:
      - setup-mpc-client
dependencies:
  - setup-mpc-common
  - setup-tools