version: '3'
services:
  setup-mpc-client:
    build:
      context: ..
      dockerfile: setup-mpc-client/Dockerfile
    image: aztec/setup-mpc-client
    tty: true
    command: ["yarn", "start:dev"]
    environment:
      SERVER_HOST: 'setup-mpc-server'
      ACCOUNT_INDEX: '0'
    volumes:
      - .:/usr/src/setup-mpc-client
      - ../setup-mpc-common/src:/usr/src/setup-mpc-client/src/setup-mpc-common

  setup-mpc-client1:
    build:
      context: ..
      dockerfile: setup-mpc-client/Dockerfile
    image: aztec/setup-mpc-client
    tty: true
    command: ["yarn", "start:dev"]
    environment:
      SERVER_HOST: 'setup-mpc-server'
      ACCOUNT_INDEX: '1'
    volumes:
      - .:/usr/src/setup-mpc-client
      - ../setup-mpc-common/src:/usr/src/setup-mpc-client/src/setup-mpc-common

  setup-mpc-server:
    build:
      context: ..
      dockerfile: setup-mpc-server/Dockerfile
    image: aztec/setup-mpc-server
    environment:
      YOU_INDICIES: '0,1'
    expose:
      - 80
    ports:
      - "8081:80"
    volumes:
      - ../setup-mpc-server:/usr/src/setup-mpc-server
      - ../setup-mpc-common/src:/usr/src/setup-mpc-server/src/setup-mpc-common

  setup-mpc-web:
    build:
      context: ..
      dockerfile: setup-mpc-web/Dockerfile
    image: aztec/setup-mpc-web
    environment:
      PORT: '80'
    expose:
      - 80
    ports:
      - "8080:80"
    volumes:
      - ../setup-mpc-web:/usr/src/setup-mpc-web