version: '3'
services:
  setup-mpc-client:
    build: .
    image: aztecprotocol/setup-mpc-client
    tty: true
    environment:
      API_URL: 'http://setup-mpc-server/api'
      PRIVATE_KEY: '0xf90214f59d15c663d4d13b06b115838ee8a397af1dbf6535479a818d6e32a26a'
    volumes:
      - .:/usr/src/setup-mpc-client
      - ../setup-mpc-common:/usr/src/setup-mpc-client/node_modules/setup-mpc-common

  setup-mpc-client1:
    build: .
    image: aztecprotocol/setup-mpc-client
    tty: true
    environment:
      API_URL: 'http://setup-mpc-server/api'
      PRIVATE_KEY: '0xf64420705123ff35ad7c8129018603ba617967543ba08702d1786c54818daeb3'
    volumes:
      - .:/usr/src/setup-mpc-client
      - ../setup-mpc-common:/usr/src/setup-mpc-client/node_modules/setup-mpc-common

  setup-mpc-server:
    build:
      context: ..
      dockerfile: setup-mpc-server/Dockerfile
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-server
    environment:
      YOU_INDICIES: '0,1'
      STORE_PATH: './store'
      TMP_PATH: './store/tmp'
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ../setup-mpc-server:/usr/src/setup-mpc-server
      - ../setup-mpc-common:/usr/src/setup-mpc-server/node_modules/setup-mpc-common

  setup-mpc-web:
    build:
      context: ..
      dockerfile: setup-mpc-web/Dockerfile
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-web
    environment:
      PORT: '80'
    expose:
      - 80
    ports:
      - "8080:80"
    volumes:
      - ../setup-mpc-web:/usr/src/setup-mpc-web