version: '3'
services:
  setup-mpc-client:
    build: .
    image: aztecprotocol/setup-mpc-client
    tty: true
    environment:
      API_URL: 'http://setup-mpc-server/api'
      PRIVATE_KEY: '0xf90214f59d15c663d4d13b06b115838ee8a397af1dbf6535479a818d6e32a26a'
    volumes:
      - .:/usr/src/setup-mpc-client
      - ../setup-mpc-common:/usr/src/setup-mpc-client/node_modules/setup-mpc-common

networks:
  default:
    external:
      name: setup_default
