name: setup-mpc-webterm
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-webterm
      - '278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-common:latest aztecprotocol/setup-mpc-client:latest'
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-webterm
dependencies:
  - setup-mpc-common
  - setup-mpc-client
