name: setup-post-process
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - 278380418400.dkr.ecr.us-east-2.amazonaws.com/setup-post-process
      - 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-tools:latest
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-post-process
      - '-'
      - us-east-2
dependencies:
  - setup-tools
