name: setup-post-process
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - setup-post-process
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-post-process
      - '-'
      - us-east-2
dependencies:
  - setup-tools
